package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/chaojimct/cli-agent-gateway/internal/config"
)

const wizardIntro = `  ╔════════════════════════════════════════════════════╗
  ║        Welcome to CLI Agent Gateway!              ║
  ║        First-time setup wizard                    ║
  ╚════════════════════════════════════════════════════╝

  This wizard will help you configure the gateway.
  Press Enter to accept defaults (shown in brackets).
`

// runWizard runs the first-time setup wizard and writes config.local.yaml.
// Returns true if config was created.
func runWizard() bool {
	configDir, err := config.UserConfigDir()
	if err != nil {
		return false
	}
	localPath := filepath.Join(configDir, "config.local.yaml")

	// Only wizard if no local config exists yet
	if fileExists(localPath) {
		return false
	}

	fmt.Fprint(os.Stderr, wizardIntro)

	scanner := bufio.NewScanner(os.Stdin)
	readLine := func(prompt string) string {
		fmt.Fprintf(os.Stderr, "  %s ", prompt)
		if scanner.Scan() {
			return strings.TrimSpace(scanner.Text())
		}
		return ""
	}

	// Q1: Server port
	port := readLine("Server port [8080]:")
	if port == "" {
		port = "8080"
	}

	// Q2: Proxy
	proxy := readLine("HTTP proxy (leave empty to skip) []:")

	// Q3: Default model
	model := readLine("Default model [auto]:")
	if model == "" {
		model = "auto"
	}

	// Q4: Agent mode
	mode := readLine("Agent mode (plan/ask) [ask]:")
	if mode == "" {
		mode = "ask"
	}
	if mode != "plan" && mode != "ask" {
		mode = "ask"
	}

	// Q5: Auth
	authInput := readLine("Enable API key auth? (y/N) [N]:")
	authEnabled := strings.ToLower(authInput) == "y" || strings.ToLower(authInput) == "yes"
	apiKey := ""
	if authEnabled {
		apiKey = readLine("API key:")
	}

	// Build config.local.yaml
	var cfg strings.Builder
	cfg.WriteString("# Generated by first-run wizard\n\n")
	cfg.WriteString("cursor:\n")
	cfg.WriteString("  binary_path: cursor-agent\n")
	cfg.WriteString(fmt.Sprintf("  default_model: %s\n", model))
	fmt.Fprintf(&cfg, "  client_tools_agent_mode: %s\n", mode)
	if proxy != "" {
		fmt.Fprintf(&cfg, "  proxy: %s\n", proxy)
	}
	cfg.WriteString("\n")
	cfg.WriteString("server:\n")
	fmt.Fprintf(&cfg, "  port: %s\n", port)
	cfg.WriteString("\n")
	if authEnabled {
		cfg.WriteString("auth:\n")
		cfg.WriteString("  enabled: true\n")
		if apiKey != "" {
			fmt.Fprintf(&cfg, "  api_key: \"%s\"\n", apiKey)
		}
	}

	// Ensure config dir exists
	_ = os.MkdirAll(configDir, 0o700)

	if err := os.WriteFile(localPath, []byte(cfg.String()), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "  Failed to write config: %v\n", err)
		return false
	}

	fmt.Fprintf(os.Stderr, "\n  Config saved to: %s\n\n", localPath)
	return true
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// hasExistingConfig checks if any config file exists before default generation.
func hasExistingConfig() bool {
	// Check cwd
	if cwd, err := os.Getwd(); err == nil {
		if fileExists(filepath.Join(cwd, config.DefaultConfigFileName)) {
			return true
		}
	}
	// Check user config dir
	if dir, err := config.UserConfigDir(); err == nil {
		if fileExists(filepath.Join(dir, config.DefaultConfigFileName)) {
			return true
		}
		if fileExists(filepath.Join(dir, "config.local.yaml")) {
			return true
		}
	}
	return false
}
